---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# qpcr.CFX.process

<!-- badges: start -->
<!-- badges: end -->

The goal of qpcr.CFX.process is to ...

## Installation

You can install the development version of qpcr.CFX.process from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dimitriskokoretsis/qpcr.CFX.process")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r}
Cq.data <- data.table::fread("test_data/PCR_Cq_data.csv",check.names=TRUE)
```


```{r}
library(qpcr.CFX.process)
qPCR.analysis <- qPCR_analysis_wrap(Cq.data,refgene="reference.gene",control="control.condition")
```

```{r}
str(qPCR.analysis,max.level=1)
```

```{r}
qPCR.analysis$NTC
```

```{r}
str(qPCR.analysis$std.curve,max.level=1)
```

```{r}
knitr::kable(qPCR.analysis$std.curve$data)
knitr::kable(qPCR.analysis$std.curve$efficiencies)
qPCR.analysis$std.curve$plot
```


```{r}
knitr::kable(qPCR.analysis$unk.rxn)
```

```{r}
knitr::kable(qPCR.analysis$expression)
```



```{r}
library(datavis)
expression.plot <- qPCR.analysis$expression |>
  bar_point_plot(x="Target",
                 y="fold.change",
                 color.group="Sample",
                 mean.type="geometric")

expression.plot
```


